sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qw123456

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0


  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tLFfkwknDJygayP4yea
    access-key-secret: 1JKOhDICJXeA58M6j4ZDKEBOjQKyDZ
    bucket-name: glx-db

  wechat:
    appid: wxa2296592dbe5b3b0
    secret: eacd0955f6c28a433079e5686f96c4af